### ISSUE TITLE
Beta kit program

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#21]
Circling back to reengage with a refined version of the alpha kit
- [x] recontacting alpha group
- [x] collect feedback
- [x] reincorporate into beta kit
- [x] reorder beta kit parts
- [x] recruit into beta program
- [x] synchronize with KS & MZ
- [x] develop workshop formats as in #5 for this
- [x] ship limited beta kits (chris f, gretchen, surfrider, dave s, stevie, jeff, soon Yagiz)
- [x] get limited beta feedback (finish by May 31, @gretchengehrke & @steviepubliclab) and incorporate into #7 
- [x] prep to fill and ship oils
- [x] choose final oils for kit (including MC252/Deepwater Horizon tarballs?) 
- [x] SpectralWorkbench macro and comparison issues (@mathewlippincott  for @jywarren)
  - [x] publiclab/spectral-workbench#118 - graphing lots of samples
  - [x] saving results of a whole OTK runthrough (@mathewlippincott elaborates in SW issue)
- [x] determine scope of full beta program (@mathewlippincott)
  - 50?
- [x] instructions for beta program members (@gretchengehrke building on @jywarren in #24)
  - take 3x spectra of all ref and unlabeled samples
  - due May 31
- [x] recruit for full beta program
  - [x] existing customers
  - [x] ppl w/ lab access @gretchengehrke
- [x] begin production of full beta kits
- [x] ship full beta kits
- [x] followup w/ beta testers (via a fellowship in #28, completes #8?)
- [x] confidence interval testing (#23) -- kits tested by collaborators for calibration & accuracy, and limitations
- [x] review begins, preparing materials and another iteration for use in monthly meetups in Q4.
- [x] August 2015: integrate changes and re-release
## Questions to answer via @mathewlippincott:
- [x] do we need to design an integrated spectrometer/OTK frame?
- [ ] Is this kit field ready? its paper, people want to use it in marine environments.  Can we encapsulate it/weatherpoof it, or should we make it from waterproof material? 
- [x] can we collect samples off of the water? (will be answered by new fellowship)
- [ ] what grades of oil do we need?
  - [ ] oil grades 40w- look at
  - [ ] are all oils of the same grade equivalent? do we need to settle on a brand of neat oils?
- [ ] how do we get marine diesel? where do we get bunker fuel? do we need these?
- [ ] how do people store samples?
  - [ ] can they pour cuvettes back?
  - [ ] can they seal the tops with silicone tape? 
- [ ] how do we recommend disposal? at a gas station or mailback to us?
  - http://www.epa.gov/osw/conserve/materials/usedoil/index.htm
  - http://www.epa.gov/osw/conserve/materials/usedoil/usedoil.htm
  - http://www.earth911.com/ - search for recycling centers
  - American Petroleum Institute site on recycling oil: http://www.recycleoil.org/
  - http://search.earth911.com/?what=Gas%2FOil+Mixture&where=02145
- [ ] Does every tester need to test reference samples with every try? are fluorescences all relative or can we calibrate a specific OTK? 
- [ ] natural oils are still really dim.  is that enough to say “hey its dim its probably fish oil?”
- [ ] are differences between diesel fuel (B80, etc) so big that we need multiple samplse?
- [ ] what crudes do we need?
  - [ ] how do we get gulf of mexico crude? currently have to drive and pick it up. (not for beta program)
- [ ] can we consistently identify road asphalt?

**Comment by jywarren** [comment]
@mathewlippincott just looping you in here; this is a rough to-do list Stevie and I put together for the beta kits program

**Comment by jywarren** [comment]
@stevie is getting nail polish bottles for the July 31 NOLA event.

**Comment by steviepubliclab** [comment]
So far I have 25 nail polish bottles, 7 french bottles and whatever @mathewlippincott is bringing for bottles

**Comment by jywarren** [comment]
super duper! Can you upload a photo to
http://publiclab.org/notes/stevie/07-09-2014/a-new-orleans-event-samples-with-spectrometry
so we can see the bottles?

**Comment by steviepubliclab** [comment]
Mathew has bottles with him right?

**Comment by jywarren** [comment]
yep!

**Comment by steviepubliclab** [comment]
Added the email communication from the Alpha kit outreach on this doc: 
https://docs.google.com/document/d/16tHQFsFo4WgzmHXaUhKRj3yg8LfP86KCwMCz3hSKnv8/edit

**Comment by mathewlippincott** [comment]
determining confidence interval

**Comment by jywarren** [comment]
http://publiclab.org/notes/mathew/04-07-2015/assembling-the-oil-testing-kit-cuvette-frame cuvette frames shipping shortly!
